module:
  mounts:
    - source: content
      target: content/styleguide
      lang: en
    - source: layouts
      target: layouts/styleguide
    - source: partials
      target: layouts/partials/tnd-styleguide
